name: Convert Markdown to HTML

on:
  push:
    paths:
      - '**/*.md'
  workflow_dispatch:

jobs:
  convert-markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Converts Markdown to HTML
        uses: jaywcjlove/markdown-to-html-cli@v5.0.3
        with:
          source: about-me.md
          output: about-me.html

      - name: commit changes
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          if [ -n "$(git status --porcelain)" ]; then
            git add about-me.html
            git commit -m "About me page updated"
            echo ::set-output name=exit_code::0
          else
            echo ::set-output name=exit_code::1
          fi

      - name: Push changes
        if: steps.commit.outputs.exit_code == '0'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}