name: Close Pull Request

on:
  pull_request_target:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  close:
    runs-on: ubuntu-latest
    if: github.actor != github.repository_owner
    steps:
      - uses: superbrothers/close-pull-request@9c18513d320d7b2c7185fb93396d0c664d5d8448  # v3
        with:
          comment: |
            Thanks for your interest! This repository does not accept pull requests.

            If you've found a bug or have a suggestion, please open an issue instead.
